FROM node:12
COPY nodeapp /nodeapp
WORKDIR /nodeapp
ENV RDS_HOSTNAME=env.RDS_HOSTNAME
ENV RDS_USERNAME=env.RDS_USERNAME
ENV RDS_PASSWORD=env.RDS_PASSWORD
ENV RDS_PORT=3306
ENV REDIS_PORT=env.REDIS_PORT
ENV REDIS_HOSTNAME =env.REDIS_HOSTNAME

RUN npm install
CMD ["node", "/nodeapp/app.js"]